name: Docs Skip CI

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Docker check
        run: echo "Skipping check for documentation change"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Test check
        run: echo "Skipping check for documentation change"

  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Skip CodeQL check
        run: echo "Skipping check for documentation change"
